channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - bson=0.5.10
  - numpy=1.21.2
  - pandas=1.3.2
  - rouge-score=0.0.4
  - sentencepiece=0.1.96
  - torch=1.9.0
  - transformers=4.9.2